apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: emergencias
  labels:
    app: api-gateway
data:
  NODE_ENV: "production"
  PORT: "3000"
  MS_INCIDENTES_URL: "http://ms-incidentes-service:3001"
  MS_RECURSOS_URL: "http://ms-recursos-service:8000"
  GRAPHQL_PLAYGROUND: "false"
  LOG_LEVEL: "info"