apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: emergencias
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: api-gateway