apiVersion: v1
kind: Service
metadata:
  name: ms-incidentes-service
  namespace: emergencias
  labels:
    app: ms-incidentes
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: ms-incidentes